### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by xAffan** [GeyserMC/Hurricane#15]
Please support 1.20.1

**Comment by MyBlueHorizon** [comment]
you can change the version in fabric.mod.json to work.

**Comment by xAffan** [comment]
I hope the change can be pushed though.

**Comment by onebeastchris** [comment]
> you can change the version in fabric.mod.json to work.

This is the spigot/paper plugin; there is no fabric.mod.json - p.s., hurricane-fabric is in a separate repository, and was updated to support 1.20.1 :)

**Comment by onebeastchris** [comment]
Given that this was meant for Hurricane-Fabric, I'll close this as completed.
