### ISSUE TITLE
Getting Warning for Steerable Items on 1.20.1

### ISSUE THREAD

**Issue by Arinautic** [GeyserMC/Hurricane#16]
When running this plugin on 1.20.1 (which I know isn't officially supported), I get this warning:

`[GeyserHacks] This Minecraft server version does not support the item steerable workaround!`

I feel like this may just be one line in the code that checks the version, and it wants it to be 1.19. If we could get an updated version that allows 1.20 to use this feature it would be great. Otherwise the plugin works great, just this one thing is very annoying when using GeyserMC.

**Comment by Camotoy** [comment]
It's not just a one-line code check. A later version of 1.19 changed how our steerable hack works, and I was unable to come up with a good fix for Paper.

**Comment by onebeastchris** [comment]
Geyser now supports item steerables natively, so this option is no longer needed (and removed) from new versions of hurricane. Update Geyser & Hurricane to their latest respective version to resolve this

Download Hurricane here: https://download.geysermc.org/v2/projects/hurricane/versions/latest/builds/latest/downloads/spigot
