### ISSUE TITLE
Uetate to 1.20.4

### ISSUE THREAD

**Issue by TheoMarque** [GeyserMC/Hurricane#20]
Not function properly on 1.20.4 Java and latest bedrock (1.20.60+). Probably need to add some packages from newer version but I can't add new NSM libraries usefully to plugin.

**Comment by xcomcadx** [comment]
Please do so, we beg of you.

**Comment by rtm516** [comment]
Updated to 1.20.5 in https://github.com/GeyserMC/Hurricane/commit/de9ade84a1a38d7cbbd960cc92fa1f21c8d96ce7
