### ISSUE TITLE
Add 1.20.5/6 compatibility

### ISSUE THREAD

**Issue by BrailleBennett** [GeyserMC/Hurricane#21]
This plugin currently doesn't load in 1.20.5/6 versions of the game. Since Geyser's latest supported version at time of writing is 1.20.6, it would only make sense that this project should be updated to support it as well. Especially since some fixes included here are NOT included in the main Geyser project.

**Comment by Camotoy** [comment]
Looks like the pointed dripstone hack still works, but the bamboo one does not. A fix will happen.

**Comment by Camotoy** [comment]
Fixed with [de9ade8](https://github.com/GeyserMC/Hurricane/commit/de9ade84a1a38d7cbbd960cc92fa1f21c8d96ce7).
