### ISSUE TITLE
1.20.2 Biological movement problem

### ISSUE THREAD

**Issue by starkill1213** [GeyserMC/Hurricane#22]
I am using version 1.20.2 and this plugin shows [Hurricane] This Minecraft server version does not support the item steerable workaround!

**Comment by onebeastchris** [comment]
Geyser now supports item steerables natively, so this option is no longer needed (and removed) from new versions of hurricane. Update Geyser & Hurricane to their latest respective version to resolve this.

Download Hurricane here: https://download.geysermc.org/v2/projects/hurricane/versions/latest/builds/latest/downloads/spigot
