### ISSUE TITLE
Bungee support

### ISSUE THREAD

**Issue by lolwhatdidigetbanned** [GeyserMC/Hurricane#25]
Add bungee cord support

**Comment by Camotoy** [comment]
What would this look like to you? Hurricane is pretty dependent on being installed on the server.

**Comment by lolwhatdidigetbanned** [comment]
> What would this look like to you? Hurricane is pretty dependent on being installed on the backend server.

The geyseeextra plugin support it really well, why not add a proxy-mode

**Comment by onebeastchris** [comment]
They're not comparable. Hurricane needs direct server access as it modifies aspects of the spigot/paper server directly, which is not possible to do on a proxy.

Do note that you can still use Hurricane even if Geyser is on a proxy or if you're using Geyser-Standalone - you'll just need to set up floodgate forwarding.

**Comment by letsgoawaydev** [comment]
> > What would this look like to you? Hurricane is pretty dependent on being installed on the backend server.
> 
> 
> 
> The geyseeextra plugin support it really well, why not add a proxy-mode

The reason why GeyserExtras can have a proxy mode is because the data being transferred over to the backend is quite literally only the emote ids which doesn't require any server modification.

It would not make sense for Hurricane to have a proxy-mode as if you install Hurricane on your backend server, no further changes are needed on your proxy (afaik)

**Comment by Camotoy** [comment]
Thanks for the issue anyway! Just installing Hurricane on your backend server with Floodgate (plus key forwarding set up correctly) should suffice.

**Comment by lolwhatdidigetbanned** [comment]
Why not add a thing that supports hunger by like telling people that hurricane does not work on bungee! [error] 
hurricane disabled 
*the plugin hurricane disables*

**Comment by lolwhatdidigetbanned** [comment]
> BungeeCord should already warn you if you try to load a spigot plugin on BungeeCord

A big red warning btw and some users don’t “read” it

**Comment by onebeastchris** [comment]
If users don't read Bungee's warning, they also won't read hurricane's :p
